server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: test
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.serch.mapper

eureka:
  client:
    service-url.defaultZone: http://localhost:8080/eureka

